### ISSUE TITLE
Missing "src/i18n/config" file

### ISSUE THREAD

**Issue by sanak** [ecorismap/ecorismap#10]
First of all, thanks for this really nice and interesting project!

I tried to build the code on my local environment (M1 Mac 13.0.1 (Ventura)), but I noticed the following file seems to be missing, so pushing it is really helpful. 🙇‍♂️

```sh
% yarn tsc

:
src/utils/Layer.ts:2:19 - error TS2307: Cannot find module '../i18n/config' or its corresponding type declarations.

2 import { t } from '../i18n/config';
                    ~~~~~~~~~~~~~~~~
:
```

Thanks!

**Comment by tmizu23** [comment]
Thank you for your interest in this project.

I have pushed the i18n/config file, but it is still missing a few files and probably won't build yet.
I will fix it so that you can build. Until then, please wait a little.

Thank you

**Comment by sanak** [comment]
Okay, thanks! 🙇‍♂️

**Comment by tmizu23** [comment]
I have updated some files and README for build.
Please try to build.😀

**Comment by sanak** [comment]
Okay, thanks a lot!!! 🙇‍♂️👍
I will try it over the year end/start. 😄

**Comment by sanak** [comment]
I could confirm that all env (ios/android/web) launched successfully! 😄
Thanks a lot!!! 🙇‍♂️
